In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:

emp = pd.read_csv("Palmoria Group emp-data.csv")

emp.head()

               Name  Gender   Department    Salary Location     Rating
0      Ches Bonnell    Male        Sales   88050.0    Lagos  Very Good
1  Garwin Peasegood  Female  Engineering   68220.0    Lagos       Good
2   Sidoney Yitzhok  Female          NaN  118440.0    Abuja  Not Rated
3  Saunders Blumson     NaN        Legal   56370.0   Kaduna  Very Good
4    Gardy Grigorey  Female      Support  107090.0   Kaduna       Poor

In [3]:
emp.shape

(1015, 6)

In [4]:
emp.isnull().sum()

Name           0
Gender        43
Department    28
Salary        43
Location       0
Rating         0
dtype: int64

In [5]:
for column in emp.columns:
    print("\n", column)
    print(emp[column].unique())

 Name
<StringArray>
[      'Ches Bonnell',   'Garwin Peasegood',    'Sidoney Yitzhok',
   'Saunders Blumson',     'Gardy Grigorey',    'Marlie Charsley',
  'Adella Hartshorne',        'Rasla Fisby',       'Rayna Gamlin',
        'Willi Vasey',
 ...
        'Bev Lashley',   'Madge McCloughen',      'Frasier Straw',
        'Dean Biggam',       'Husein Augar',   'Shaylyn Ransbury',
 'Christoph Stretton',     'Jordain Cyster',       'Malory Biles',
          'Adey Ryal']
Length: 940, dtype: str

 Gender
<StringArray>
['Male', 'Female', nan]
Length: 3, dtype: str

 Department
<StringArray>
[                   'Sales',              'Engineering',
                        nan,                    'Legal',
                  'Support',          'Human Resources',
                 'Services',     'Business Development',
       'Product Management',                 'Training',
 'Research and Development',               'Accounting',
                'Marketing']
Length: 13, dtype: str

 Salary
[ 88050.  68220. 118440.  56370. 107090. 108450.  41160. 109000.     nan
  43020.  37800.  88380.  84420. 101760. 110780.  68430. 105370. 113800.
  76300.  44530.  63710.  62780. 119750. 116980.  35940. 109040. 109160.
  75540.  30000.  76210. 112650. 108460.  69070. 116520.  96560.  36460.
  50950.  75440.  84760.  82240.  28330.  60580.  45510. 110770.  86920.
  84680.  36860. 114010.  54130.  81720.  84470. 114600. 114690.  57350.
  51200.  85260.  71230. 107660.  75230. 108080.  28480.  56620.  87900.
 103550.  78500.  93930. 114770.  73530.  55310.  49670.  40770. 106780.
 100730.  74620.  40450.  60560. 114900.  69860.  51320. 103600.  53540.
  98740. 115090.  51910.  34080.  88690. 109190.  89610. 109760. 108390.
  29880.  68090.  87210.  90800. 102930.  29080.  44450.  97120.  58840.
  77060.  81180.  90080.  35830.  37110. 112780.  96000. 112550.  88330.
 116770.  40270.  96640. 118100.  43600.  54520.  57750.  99970.  62200.
  42990. 117810.  58130.  86840.  41700.  72880. 117150.  97020.  67510.
  34830.  38730.  96790.  68040.  88510.  65350.  52000.  85740.  92500.
  80770.  67820.  48060.  56830.  72500.  57080. 104080.  29770.  48690.
  70080.  69190.  37920.  89120.  48140.  69340.  71330.  67620.  69740.
  44300.  40560. 115230.  39750. 108970. 112570.  56810.  42950.  42820.
 101670. 104750.  43330.  61430. 105800.  99470.  68890.  58860.  86940.
 118120.  91120.  41420.  86010.  30080.  96800.  31090.  96140.  98640.
  71510.  86490. 103240.  47550.  78490.  61050.  36370.  47290.  79650.
 119660.  43200.  89830.  91500.  29670.  75720.  81900.  42380.  32620.
  72040.  77740. 102140.  48630. 105960.  97400.  99450.  82670.  99200.
 111480.  84940.  95340.  47960.  56710.  71180.  78180.  84750.  98970.
  76560.  35930. 104410.  84600.  68800.  38660.  86560. 107340. 111050.
  75320.  57910.  29490.  52670.  48530. 105470.  98200. 106190.  52610.
  63450.  74710.  60330.  61010. 117020.  77130. 106930.  62090.  61330.
  41600. 105870. 118300.  99680. 101500.  46160.  41930.  73360. 119550.
  53240.  90880.  47670. 111420.  47760.  47650. 103360.  72160.  60800.
  74010.  60760.  74550.  32500. 110040.  99750.  92470. 109980.  41790.
  86360.  65570.  69160.  41570.  83400.  67660.  34470.  38240.  78380.
 115640.  46250.  82120. 108160. 108360.  77840.  85180.  85920. 106490.
  38520.  49530.  29610.  84170.  92190.  87850.  43700.  31820.  70230.
  96320.  90700.  67960. 103110.  59610.  66570.  74390.  67010. 109710.
 110910.  80060. 108250. 104340.  38440.  50800.  44400.  34980.  77260.
 117940.  31040. 109140.  96370.  31170. 116240. 115190.  79570.  95680.
 107110.  66100.  39960. 111850.  29890.  48170.  72840.  68970.  89090.
 118450.  80360. 104770.  70440.  56900.  72450.  34500. 118800. 115080.
  39540. 106460.  94530.  71590. 104900.  81790.  33050.  96920.  98400.
  50020.  71210.  53180. 107020.  58400.  49000.  85530.  53950.  41140.
  49920.  39700.  43900.  72700.  29420.  58280.  67980.  49760.  69910.
 112370.  28580.  43590.  78840.  61990.  77100.  66020.  70930.  40980.
  48980. 110820.  61690.  51170. 104800.  56280.  52590.  72350.  39940.
  28130.  69460. 109030.  66460.  50810. 114510.  86230.  73240.  53920.
 113690. 101790.  38930.  57090. 106170.  59550.  89960.  58850.  68200.
  90130.  45060.  66370.  85880.  59260.  61790.  48180.  74800.  31020.
  37550. 118840.  94050.  81260.  36710.  98360.  39680. 101390.  80700.
  78020. 115490. 111910. 109050. 109380.  69710.  57620. 101190. 115840.
  45450.  54140. 117520.  93210. 104470. 110890.  96660. 118360.  88030.
  87810.  51520.  60260.  61210.  52750.  47270. 118060.  37360.  66510.
  29530.  60440.  90530.  67950. 105120.  60570. 119110.  70360.  45110.
  33630.  53870. 111190.  29970.  64960. 111230.  99530.  35980.  65700.
 109170.  95020.  87290.  97110.  59430. 112120.  28160.  75870.  93270.
  42730.  80610.  69060.  31280.  96610.  37020.  54970.  41910. 116970.
  86390.  81150.  71820.  85460.  91190.  93160. 110950.  35990.  39970.
  79520.  52120.  60010.  35440. 105610. 113280.  41980. 103670.  89690.
  87620.  48250.  85780.  54010.  75480.  93500.  98630.  76390.  68010.
  58030.  59300.  51800.  57930.  40530.  48290.  63720.  84500.  67430.
 109120.  69760.  45600.  33030.  80170.  43510.  49390.  47910.  35740.
  42240.  36540.  85720.  34620.  62690.  30250. 103160. 109790.  33760.
  36740.  31240.  75730.  50860.  84200.  95980.  65920. 113620.  60140.
  92450.  34650.  84740.  88360. 116220. 106890. 107440.  29810. 105330.
  43110.  52630.  46350.  39800. 108170.  69730. 110200. 116090.  52140.
  32810.  46990.  33560.  33890.  51740.  51650. 115980.  58370. 106670.
  44850.  75600.  69120.  31200.  42160. 110830.  83180.  46750.  78540.
  77000.  74920.  36550.  95950.  77910. 116670.  71920.  39340. 103490.
  87740. 113980. 114470.  31050.  76620.  76190.  50450.  29330.  76930.
  33800.  44820.  84310. 108600.  47000.  59810.  90340.  64270. 103990.
  70380.  89020. 113750.  32720.  61920.  74600.  38030.  30940.  28870.
  87930. 101610.  28310.  89840.  96250. 112460. 115440.  33920.  46280.
  58940. 118980.  96750. 101220.  63020.  75920.  93080.  68860.  70650.
 101120.  77050.  89360.  37840.  89160.  74110.  31630.  40910.  32190.
  73490.  52220.  68900.  83750. 110970.  49520.  53910. 109870.  61620.
  57000.  70610.  51860.  60130.  58260.  70020.  35670.  67630.  82300.
 114870.  71030.  85670.  61700.  66140.  68980. 114430.  53760.  91310.
 117840.  31830.  32980.  47360.  86740.  87400.  75090.  92340.  99480.
  58830.  32140. 102520.  79590.  28970.  92700.  36150.  52960.  31920.
 104210.  40750.  98020.  96620.  40400.  81220.  33840.  75880.  81380.
  71490.  91930. 107790.  69970. 114180.  85330.  65130.  36820. 116890.
  78710.  86470.  77110.  86570. 117850. 116500.  80030.  76320. 110730.
  86990.  74410.  87610. 103340.  46470. 108290.  78640.  75990.  55280.
  98010.  50310.  91360. 115920.  56870.  75970.  52270.  39780.  58960.
  37900.  66610.  44120.  32270.  37130.  45590.  94070.  41220. 119930.
  94820.  38830.  91450.  70760.  71540. 104680.  63370. 106400.  36920.
  57820.  93740.  93960. 107220.  90150.  94020.  42970.  33410. 119670.
 115380.  75010. 104120.  82680.  52250.  83190.  83590. 107700. 102130.
  74360.  42310.  78440. 113760.  93880.  85000.  72550.  72360. 114890.
 107580.  36040.  58310.  35010.  74280. 115790.  38330.  70270.  37060.
  58100.  99780. 119020.  92940.  59670.  41000.  77470.  45650.  88430.
  36880. 111820.  92870. 100360.  48950.  52810.  78560.  75280.  93130.
 105290. 108340. 101420.  54780.  63560.  68480.  99460. 100420.  39650.
  56250.  57640.  43150. 106080.  29590.  86240.  36480.  48590.  41670.
  62280.  92010.  59560. 114810.  66870. 113790.  38250.  48090.  99630.
  86340.  88590.  61100.  71240. 114650.  76900. 116590.  78390. 103610.
  98110.  33960. 112110.  71370.  71570.  67910. 100370.  90240.  58740.]

 Location
<StringArray>
['Lagos', 'Abuja', 'Kaduna']
Length: 3, dtype: str

 Rating
<StringArray>
['Very Good', 'Good', 'Not Rated', 'Poor', 'Average', 'Very Poor']
Length: 6, dtype: str

In [6]:
emp.duplicated().sum()

np.int64(4)

In [7]:
emp[emp.duplicated(keep=False)]

                  Name  Gender   Department    Salary Location   Rating
30       Mollie Hanway    Male          NaN  112650.0    Lagos  Average
327  Delinda Snozzwell     NaN  Engineering   67010.0    Abuja     Good
516   William Reeveley    Male     Training   53870.0    Abuja     Good
694  Delinda Snozzwell     NaN  Engineering   67010.0    Abuja     Good
726         Oby Sorrel  Female      Support   58940.0   Kaduna  Average
766      Mollie Hanway    Male          NaN  112650.0    Lagos  Average
846         Oby Sorrel  Female      Support   58940.0   Kaduna  Average
934   William Reeveley    Male     Training   53870.0    Abuja     Good

In [8]:
emp = emp.drop_duplicates()

In [9]:
emp.duplicated().sum()

np.int64(0)

In [10]:
emp = emp[emp["Salary"].notna()]

In [11]:
emp["Salary"].isnull().sum()

np.int64(0)

In [12]:
emp = emp[emp["Department"].notna()]

In [13]:
emp["Department"].isnull().sum()

np.int64(0)

In [14]:
emp["Gender"] = emp["Gender"].fillna("Undisclosed")

In [15]:
emp["Gender"].value_counts()

Gender
Male           464
Female         440
Undisclosed     39
Name: count, dtype: int64

In [16]:
text_columns = [
    "Name",
    "Gender",
    "Department",
    "Location",
    "Rating"
]

for col in text_columns:
    emp[col] = emp[col].astype(str).str.strip()

In [17]:
print("Rows:", emp.shape[0])
print("Columns:", emp.shape[1])

Rows: 943
Columns: 6

In [18]:
def salary_band(salary):
    lower = int(np.floor(salary / 10000) * 10000)
    upper = lower + 10000
    return f"${lower:,} - ${upper:,}"

In [19]:
emp["Salary Band"] = emp["Salary"].apply(salary_band)

In [20]:
emp[["Salary", "Salary Band"]].head(20)

      Salary          Salary Band
0    88050.0    $80,000 - $90,000
1    68220.0    $60,000 - $70,000
3    56370.0    $50,000 - $60,000
4   107090.0  $100,000 - $110,000
5   108450.0  $100,000 - $110,000
6    41160.0    $40,000 - $50,000
7   109000.0  $100,000 - $110,000
9    43020.0    $40,000 - $50,000
10   37800.0    $30,000 - $40,000
11   88380.0    $80,000 - $90,000
12   84420.0    $80,000 - $90,000
13  101760.0  $100,000 - $110,000
14  110780.0  $110,000 - $120,000
15   68430.0    $60,000 - $70,000
16  105370.0  $100,000 - $110,000
17  113800.0  $110,000 - $120,000
18   76300.0    $70,000 - $80,000
19   44530.0    $40,000 - $50,000
20   63710.0    $60,000 - $70,000
21   62780.0    $60,000 - $70,000

In [21]:
emp.head()

,Name,Gender,Department,Salary,Location,Rating,Salary Band
0,Ches Bonnell,Male,Sales,88050.0,Lagos,Very Good,"$80,000 - $90,000"
1,Garwin Peasegood,Female,Engineering,68220.0,Lagos,Good,"$60,000 - $70,000"
3,Saunders Blumson,Undisclosed,Legal,56370.0,Kaduna,Very Good,"$50,000 - $60,000"
4,Gardy Grigorey,Female,Support,107090.0,Kaduna,Poor,"$100,000 - $110,000"
5,Marlie Charsley,Male,Support,108450.0,Abuja,Poor,"$100,000 - $110,000"

In [22]:
emp["Meets $90k Requirement"] = np.where(
    emp["Salary"] >= 90000,
    "Yes",
    "No"
)

In [23]:
emp["Meets $90k Requirement"].value_counts()

Meets $90k Requirement
No     651
Yes    292
Name: count, dtype: int64

In [24]:
emp.head()

,Name,Gender,Department,Salary,Location,Rating,Salary Band,Meets $90k Requirement
0,Ches Bonnell,Male,Sales,88050.0,Lagos,Very Good,"$80,000 - $90,000",No
1,Garwin Peasegood,Female,Engineering,68220.0,Lagos,Good,"$60,000 - $70,000",No
3,Saunders Blumson,Undisclosed,Legal,56370.0,Kaduna,Very Good,"$50,000 - $60,000",No
4,Gardy Grigorey,Female,Support,107090.0,Kaduna,Poor,"$100,000 - $110,000",Yes
5,Marlie Charsley,Male,Support,108450.0,Abuja,Poor,"$100,000 - $110,000",Yes

In [25]:
emp["Meets $90k Requirement"].value_counts(normalize=True) * 100

Meets $90k Requirement
No     69.034995
Yes    30.965005
Name: proportion, dtype: float64

In [26]:
bonus = pd.read_excel("Palmoria Group Bonus Rules.xlsx")

bonus.head(10)

                 Department  Very Poor   Poor  Average   Good  Very Good
0                     Sales      0.005  0.012    0.021  0.051      0.088
1               Engineering      0.005  0.011    0.035  0.043      0.061
2                     Legal      0.005  0.019    0.021  0.054      0.064
3                   Support      0.005  0.010    0.028  0.049      0.076
4           Human Resources      0.005  0.013    0.027  0.054      0.076
5      Business Development      0.005  0.018    0.024  0.050      0.073
6        Product Management      0.005  0.010    0.032  0.041      0.062
7                  Training      0.005  0.019    0.040  0.059      0.063
8  Research and Development      0.005  0.020    0.033  0.054      0.084
9                Accounting      0.005  0.012    0.020  0.058      0.071

In [27]:
rating_columns = [
    "Very Poor",
    "Poor",
    "Average",
    "Good",
    "Very Good"
]

for col in rating_columns:
    bonus[col] = pd.to_numeric(
        bonus[col],
        errors="coerce"
    )

In [28]:
bonus

                  Department  Very Poor   Poor  Average   Good  Very Good
0                      Sales      0.005  0.012    0.021  0.051      0.088
1                Engineering      0.005  0.011    0.035  0.043      0.061
2                      Legal      0.005  0.019    0.021  0.054      0.064
3                    Support      0.005  0.010    0.028  0.049      0.076
4            Human Resources      0.005  0.013    0.027  0.054      0.076
5       Business Development      0.005  0.018    0.024  0.050      0.073
6         Product Management      0.005  0.010    0.032  0.041      0.062
7                   Training      0.005  0.019    0.040  0.059      0.063
8   Research and Development      0.005  0.020    0.033  0.054      0.084
9                 Accounting      0.005  0.012    0.020  0.058      0.071
10                  Services      0.005  0.015    0.023  0.053      0.072
11                 Marketing      0.005  0.013    0.035  0.058      0.099

In [29]:
bonus_long = bonus.melt(
    id_vars="Department",
    var_name="Rating",
    value_name="Bonus %"
)

In [30]:
bonus_long

                  Department     Rating  Bonus %
0                      Sales  Very Poor    0.005
1                Engineering  Very Poor    0.005
2                      Legal  Very Poor    0.005
3                    Support  Very Poor    0.005
4            Human Resources  Very Poor    0.005
5       Business Development  Very Poor    0.005
6         Product Management  Very Poor    0.005
7                   Training  Very Poor    0.005
8   Research and Development  Very Poor    0.005
9                 Accounting  Very Poor    0.005
10                  Services  Very Poor    0.005
11                 Marketing  Very Poor    0.005
12                     Sales       Poor    0.012
13               Engineering       Poor    0.011
14                     Legal       Poor    0.019
15                   Support       Poor    0.010
16           Human Resources       Poor    0.013
17      Business Development       Poor    0.018
18        Product Management       Poor    0.010
19                  Training       Poor    0.019
20  Research and Development       Poor    0.020
21                Accounting       Poor    0.012
22                  Services       Poor    0.015
23                 Marketing       Poor    0.013
24                     Sales    Average    0.021
25               Engineering    Average    0.035
26                     Legal    Average    0.021
27                   Support    Average    0.028
28           Human Resources    Average    0.027
29      Business Development    Average    0.024
30        Product Management    Average    0.032
31                  Training    Average    0.040
32  Research and Development    Average    0.033
33                Accounting    Average    0.020
34                  Services    Average    0.023
35                 Marketing    Average    0.035
36                     Sales       Good    0.051
37               Engineering       Good    0.043
38                     Legal       Good    0.054
39                   Support       Good    0.049
40           Human Resources       Good    0.054
41      Business Development       Good    0.050
42        Product Management       Good    0.041
43                  Training       Good    0.059
44  Research and Development       Good    0.054
45                Accounting       Good    0.058
46                  Services       Good    0.053
47                 Marketing       Good    0.058
48                     Sales  Very Good    0.088
49               Engineering  Very Good    0.061
50                     Legal  Very Good    0.064
51                   Support  Very Good    0.076
52           Human Resources  Very Good    0.076
53      Business Development  Very Good    0.073
54        Product Management  Very Good    0.062
55                  Training  Very Good    0.063
56  Research and Development  Very Good    0.084
57                Accounting  Very Good    0.071
58                  Services  Very Good    0.072
59                 Marketing  Very Good    0.099

In [31]:
emp = emp.merge(
    bonus_long,
    on=["Department", "Rating"],
    how="left"
)

In [32]:
emp.head()

,Name,Gender,Department,Salary,Location,Rating,Salary Band,Meets $90k Requirement,Bonus %
0,Ches Bonnell,Male,Sales,88050.0,Lagos,Very Good,"$80,000 - $90,000",No,0.088
1,Garwin Peasegood,Female,Engineering,68220.0,Lagos,Good,"$60,000 - $70,000",No,0.043
2,Saunders Blumson,Undisclosed,Legal,56370.0,Kaduna,Very Good,"$50,000 - $60,000",No,0.064
3,Gardy Grigorey,Female,Support,107090.0,Kaduna,Poor,"$100,000 - $110,000",Yes,0.010
4,Marlie Charsley,Male,Support,108450.0,Abuja,Poor,"$100,000 - $110,000",Yes,0.010

In [33]:
emp["Bonus %"].isnull().sum()

np.int64(71)

In [34]:
emp["Bonus"] = emp["Salary"] * emp["Bonus %"]

In [35]:
emp.head()

,Name,Gender,Department,Salary,Location,Rating,Salary Band,Meets $90k Requirement,Bonus %,Bonus
0,Ches Bonnell,Male,Sales,88050.0,Lagos,Very Good,"$80,000 - $90,000",No,0.088,7748.40
1,Garwin Peasegood,Female,Engineering,68220.0,Lagos,Good,"$60,000 - $70,000",No,0.043,2933.46
2,Saunders Blumson,Undisclosed,Legal,56370.0,Kaduna,Very Good,"$50,000 - $60,000",No,0.064,3607.68
3,Gardy Grigorey,Female,Support,107090.0,Kaduna,Poor,"$100,000 - $110,000",Yes,0.010,1070.90
4,Marlie Charsley,Male,Support,108450.0,Abuja,Poor,"$100,000 - $110,000",Yes,0.010,1084.50

In [36]:
emp["Bonus %"] = emp["Bonus %"].fillna(0)

In [37]:
emp["Bonus"] = emp["Salary"] * emp["Bonus %"]

In [38]:
emp["Total Compensation"] = (
    emp["Salary"] + emp["Bonus"]
)

In [39]:
emp.head()

,Name,Gender,Department,Salary,Location,Rating,Salary Band,Meets $90k Requirement,Bonus %,Bonus,Total Compensation
0,Ches Bonnell,Male,Sales,88050.0,Lagos,Very Good,"$80,000 - $90,000",No,0.088,7748.40,95798.40
1,Garwin Peasegood,Female,Engineering,68220.0,Lagos,Good,"$60,000 - $70,000",No,0.043,2933.46,71153.46
2,Saunders Blumson,Undisclosed,Legal,56370.0,Kaduna,Very Good,"$50,000 - $60,000",No,0.064,3607.68,59977.68
3,Gardy Grigorey,Female,Support,107090.0,Kaduna,Poor,"$100,000 - $110,000",Yes,0.010,1070.90,108160.90
4,Marlie Charsley,Male,Support,108450.0,Abuja,Poor,"$100,000 - $110,000",Yes,0.010,1084.50,109534.50

In [40]:
emp.to_csv(
    "Palmoria_Cleaned_Employee_Data.csv",
    index=False
)

In [41]:
# actual HR analysis

In [42]:
# Gender distribution
gender_distribution = (
    emp["Gender"]
    .value_counts()
    .reset_index()
)

gender_distribution.columns = [
    "Gender",
    "Employees"
]

gender_distribution

        Gender  Employees
0         Male        464
1       Female        440
2  Undisclosed         39

In [43]:
# Gender distribution %
gender_distribution["Percentage"] = (
    gender_distribution["Employees"]
    / gender_distribution["Employees"].sum()
    * 100
)

gender_distribution

        Gender  Employees  Percentage
0         Male        464   49.204666
1       Female        440   46.659597
2  Undisclosed         39    4.135737

In [44]:
# Gender by region
gender_region = pd.crosstab(
    emp["Location"],
    emp["Gender"]
)

gender_region

Gender    Female  Male  Undisclosed
Location
Abuja        158   158           17
Kaduna       164   182           14
Lagos        118   124            8

In [45]:
# Gender by region %
gender_region_pct = pd.crosstab(
    emp["Location"],
    emp["Gender"],
    normalize="index"
) * 100

gender_region_pct

Gender       Female       Male  Undisclosed
Location
Abuja     47.447447  47.447447     5.105105
Kaduna    45.555556  50.555556     3.888889
Lagos     47.200000  49.600000     3.200000

In [46]:
# Gender by department
gender_department = pd.crosstab(
    emp["Department"],
    emp["Gender"]
)

gender_department

Gender                    Female  Male  Undisclosed
Department
Accounting                    28    37            2
Business Development          41    37            3
Engineering                   38    36            5
Human Resources               41    38            3
Legal                         34    49            5
Marketing                     31    33            1
Product Management            41    47            1
Research and Development      38    31            5
Sales                         36    40            4
Services                      42    37            3
Support                       34    42            4
Training                      36    37            3

In [47]:
# Gender by department
gender_department_pct = pd.crosstab(
    emp["Department"],
    emp["Gender"],
    normalize="index"
) * 100

gender_department_pct

Gender                       Female       Male  Undisclosed
Department
Accounting                41.791045  55.223881     2.985075
Business Development      50.617284  45.679012     3.703704
Engineering               48.101266  45.569620     6.329114
Human Resources           50.000000  46.341463     3.658537
Legal                     38.636364  55.681818     5.681818
Marketing                 47.692308  50.769231     1.538462
Product Management        46.067416  52.808989     1.123596
Research and Development  51.351351  41.891892     6.756757
Sales                     45.000000  50.000000     5.000000
Services                  51.219512  45.121951     3.658537
Support                   42.500000  52.500000     5.000000
Training                  47.368421  48.684211     3.947368

In [48]:
# Performance ratings by gender
rating_gender = pd.crosstab(
    emp["Rating"],
    emp["Gender"]
)

rating_gender

Gender     Female  Male  Undisclosed
Rating
Average       189   212           18
Good           89    81            8
Not Rated      35    34            2
Poor           58    70            3
Very Good      49    36            5
Very Poor      20    31            3

In [49]:
# Performance ratings by gender %
rating_gender_pct = pd.crosstab(
    emp["Rating"],
    emp["Gender"],
    normalize="columns"
) * 100

rating_gender_pct

Gender        Female       Male  Undisclosed
Rating
Average    42.954545  45.689655    46.153846
Good       20.227273  17.456897    20.512821
Not Rated   7.954545   7.327586     5.128205
Poor       13.181818  15.086207     7.692308
Very Good  11.136364   7.758621    12.820513
Very Poor   4.545455   6.681034     7.692308

In [50]:
# Salary by gender
salary_gender = (
    emp.groupby("Gender")["Salary"]
    .agg(["count", "mean", "median", "min", "max"])
    .round(2)
)

salary_gender

             count      mean   median      min       max
Gender
Female         440  72165.68  72600.0  28310.0  119930.0
Male           464  74834.61  73820.0  28130.0  119670.0
Undisclosed     39  78658.72  75990.0  34620.0  118800.0

In [51]:
# Calculate gender pay gap
avg_male_salary = emp.loc[
    emp["Gender"] == "Male",
    "Salary"
].mean()

avg_female_salary = emp.loc[
    emp["Gender"] == "Female",
    "Salary"
].mean()

pay_gap = (
    (avg_male_salary - avg_female_salary)
    / avg_male_salary
) * 100

print(f"Male average salary: ${avg_male_salary:,.2f}")
print(f"Female average salary: ${avg_female_salary:,.2f}")
print(f"Gender pay gap: {pay_gap:.2f}%")

Male average salary: $74,834.61
Female average salary: $72,165.68
Gender pay gap: 3.57%

In [52]:
# Pay gap by region
salary_region_gender = (
    emp.groupby(["Location", "Gender"])["Salary"]
    .mean()
    .reset_index()
)

salary_region_gender

  Location       Gender        Salary
0    Abuja       Female  70452.025316
1    Abuja         Male  73368.164557
2    Abuja  Undisclosed  74812.352941
3   Kaduna       Female  72379.207317
4   Kaduna         Male  74849.945055
5   Kaduna  Undisclosed  78642.857143
6    Lagos       Female  74163.474576
7    Lagos         Male  76680.645161
8    Lagos  Undisclosed  86860.000000

In [53]:
# Pay gap by region, To make it easier to compare:
salary_region_gender_pivot = (
    salary_region_gender
    .pivot(
        index="Location",
        columns="Gender",
        values="Salary"
    )
)

salary_region_gender_pivot

Gender          Female          Male   Undisclosed
Location
Abuja     70452.025316  73368.164557  74812.352941
Kaduna    72379.207317  74849.945055  78642.857143
Lagos     74163.474576  76680.645161  86860.000000

In [54]:
# Pay gap by department
salary_department_gender = (
    emp.groupby(["Department", "Gender"])["Salary"]
    .mean()
    .reset_index()
)

salary_department_gender

                  Department       Gender         Salary
0                 Accounting       Female   72938.928571
1                 Accounting         Male   77530.000000
2                 Accounting  Undisclosed  102560.000000
3       Business Development       Female   74627.804878
4       Business Development         Male   82016.486486
5       Business Development  Undisclosed   49956.666667
6                Engineering       Female   75422.105263
7                Engineering         Male   67916.944444
8                Engineering  Undisclosed   78626.000000
9            Human Resources       Female   66578.780488
10           Human Resources         Male   73796.052632
11           Human Resources  Undisclosed   94283.333333
12                     Legal       Female   68506.764706
13                     Legal         Male   72997.959184
14                     Legal  Undisclosed   76774.000000
15                 Marketing       Female   79107.741935
16                 Marketing         Male   73701.818182
17                 Marketing  Undisclosed  105870.000000
18        Product Management       Female   70773.170732
19        Product Management         Male   76100.851064
20        Product Management  Undisclosed   36480.000000
21  Research and Development       Female   66603.947368
22  Research and Development         Male   69062.580645
23  Research and Development  Undisclosed   78614.000000
24                     Sales       Female   70406.666667
25                     Sales         Male   72039.750000
26                     Sales  Undisclosed   89125.000000
27                  Services       Female   73075.476190
28                  Services         Male   79456.216216
29                  Services  Undisclosed   67066.666667
30                   Support       Female   72415.000000
31                   Support         Male   77414.523810
32                   Support  Undisclosed   76225.000000
33                  Training       Female   77082.222222
34                  Training         Male   74896.216216
35                  Training  Undisclosed   84943.333333

In [55]:
# Pay gap by department, To make it easier to compare:
salary_department_gender_pivot = (
    salary_department_gender
    .pivot(
        index="Department",
        columns="Gender",
        values="Salary"
    )
)

salary_department_gender_pivot

Gender                          Female          Male    Undisclosed
Department
Accounting                72938.928571  77530.000000  102560.000000
Business Development      74627.804878  82016.486486   49956.666667
Engineering               75422.105263  67916.944444   78626.000000
Human Resources           66578.780488  73796.052632   94283.333333
Legal                     68506.764706  72997.959184   76774.000000
Marketing                 79107.741935  73701.818182  105870.000000
Product Management        70773.170732  76100.851064   36480.000000
Research and Development  66603.947368  69062.580645   78614.000000
Sales                     70406.666667  72039.750000   89125.000000
Services                  73075.476190  79456.216216   67066.666667
Support                   72415.000000  77414.523810   76225.000000
Training                  77082.222222  74896.216216   84943.333333

In [56]:
# $90k compliance by region
compliance_region = pd.crosstab(
    emp["Location"],
    emp["Meets $90k Requirement"]
)

compliance_region

Meets $90k Requirement   No  Yes
Location
Abuja                   236   97
Kaduna                  249  111
Lagos                   166   84

In [57]:
# $90k compliance by region %
compliance_region_pct = pd.crosstab(
    emp["Location"],
    emp["Meets $90k Requirement"],
    normalize="index"
) * 100

compliance_region_pct

Meets $90k Requirement         No        Yes
Location
Abuja                   70.870871  29.129129
Kaduna                  69.166667  30.833333
Lagos                   66.400000  33.600000

In [58]:
# Salary bands - Overall
salary_bands = (
    emp["Salary Band"]
    .value_counts()
    .sort_index()
)

salary_bands

Salary Band
$100,000 - $110,000    105
$110,000 - $120,000     97
$20,000 - $30,000       26
$30,000 - $40,000      103
$40,000 - $50,000      105
$50,000 - $60,000       94
$60,000 - $70,000       98
$70,000 - $80,000      117
$80,000 - $90,000      108
$90,000 - $100,000      90
Name: count, dtype: int64

In [59]:
# Salary bands by region

salary_bands_region = pd.crosstab(
    emp["Salary Band"],
    emp["Location"]
)

salary_bands_region

Location             Abuja  Kaduna  Lagos
Salary Band
$100,000 - $110,000     39      41     25
$110,000 - $120,000     29      38     30
$20,000 - $30,000        9      11      6
$30,000 - $40,000       37      41     25
$40,000 - $50,000       45      33     27
$50,000 - $60,000       36      40     18
$60,000 - $70,000       35      37     26
$70,000 - $80,000       35      48     34
$80,000 - $90,000       39      39     30
$90,000 - $100,000      29      32     29

In [60]:
emp[
    [
        "Name",
        "Department",
        "Rating",
        "Salary",
        "Bonus %",
        "Bonus",
        "Total Compensation"
    ]
].head(20)

,Name,Department,Rating,Salary,Bonus %,Bonus,Total Compensation
0,Ches Bonnell,Sales,Very Good,88050.0,0.088,7748.40,95798.40
1,Garwin Peasegood,Engineering,Good,68220.0,0.043,2933.46,71153.46
2,Saunders Blumson,Legal,Very Good,56370.0,0.064,3607.68,59977.68
3,Gardy Grigorey,Support,Poor,107090.0,0.010,1070.90,108160.90
4,Marlie Charsley,Support,Poor,108450.0,0.010,1084.50,109534.50
5,Adella Hartshorne,Human Resources,Average,41160.0,0.027,1111.32,42271.32
6,Rasla Fisby,Legal,Very Good,109000.0,0.064,6976.00,115976.00
7,Willi Vasey,Support,Average,43020.0,0.028,1204.56,44224.56
8,Selby Hacker,Business Development,Average,37800.0,0.024,907.20,38707.20
9,Stefa Eggleston,Sales,Average,88380.0,0.021,1855.98,90235.98
10,Phylys Benitez,Product Management,Average,84420.0,0.032,2701.44,87121.44
11,Ronnie Sinyard,Legal,Good,101760.0,0.054,5495.04,107255.04
12,Axel Grigaut,Sales,Poor,110780.0,0.012,1329.36,112109.36
13,Timmi Durran,Human Resources,Good,68430.0,0.054,3695.22,72125.22
14,Minna Showler,Training,Good,105370.0,0.059,6216.83,111586.83
15,Dyanne Strafen,Engineering,Average,113800.0,0.035,3983.00,117783.00
16,Dorolice Farry,Sales,Average,76300.0,0.021,1602.30,77902.30
17,Elliot Tuplin,Sales,Average,44530.0,0.021,935.13,45465.13
18,Lion Adcock,Legal,Average,63710.0,0.021,1337.91,65047.91
19,Vic Radolf,Product Management,Very Good,62780.0,0.062,3892.36,66672.36

In [61]:
# Total bonus for employees
total_bonus = emp["Bonus"].sum()

print(f"Total company bonus: ${total_bonus:,.2f}")

Total company bonus: $2,191,569.22

In [62]:
# Bonus by region:

bonus_region = (
    emp.groupby("Location")["Bonus"]
    .agg(["sum", "mean", "count"])
    .round(2)
)

bonus_region

                sum     mean  count
Location
Abuja     795084.45  2387.64    333
Kaduna    824261.46  2289.62    360
Lagos     572223.31  2288.89    250

In [63]:
# Total compensation by region:
compensation_region = (
    emp.groupby("Location")["Total Compensation"]
    .sum()
    .round(2)
)

compensation_region

Location
Abuja     24790484.45
Kaduna    27418141.46
Lagos     19526793.31
Name: Total Compensation, dtype: float64

In [64]:
emp.info()

<class 'pandas.DataFrame'>
RangeIndex: 943 entries, 0 to 942
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Name                    943 non-null    str
 1   Gender                  943 non-null    str
 2   Department              943 non-null    str
 3   Salary                  943 non-null    float64
 4   Location                943 non-null    str
 5   Rating                  943 non-null    str
 6   Salary Band             943 non-null    str
 7   Meets $90k Requirement  943 non-null    str
 8   Bonus %                 943 non-null    float64
 9   Bonus                   943 non-null    float64
 10  Total Compensation      943 non-null    float64
dtypes: float64(4), str(7)
memory usage: 81.2 KB

In [66]:
emp.to_csv(
    "Palmoria_Tableau_Final.csv",
    index=False
)